-- CreateTable
CREATE TABLE `customers` (
    `UID` INTEGER NOT NULL,
    `LOYALTY_POINTS` INTEGER NULL DEFAULT 0,
    `PREFERRED_PAYMENT_METHOD` VARCHAR(50) NULL,
    `ORDER_HISTORY` INTEGER NULL DEFAULT 0,
    `RATING` DECIMAL(3, 2) NULL,

    PRIMARY KEY (`UID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `deliverers` (
    `UID` INTEGER NOT NULL,
    `VEHICLE_TYPE` VARCHAR(50) NULL,
    `DELIVERY_COUNT` INTEGER NULL DEFAULT 0,
    `AVERAGE_RATING` DECIMAL(3, 2) NULL,
    `WORKING_REGION` VARCHAR(100) NULL,
    `START_HOUR` TIME(0) NULL,
    `END_HOUR` TIME(0) NULL,

    PRIMARY KEY (`UID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `kitchens` (
    `UID` INTEGER NOT NULL,
    `CUISINE_TYPE` VARCHAR(50) NULL,
    `AVERAGE_PREPARATION_TIME` TIME(0) NULL,
    `RATING` DECIMAL(3, 2) NULL,
    `ACTIVE_STATUS` BOOLEAN NULL DEFAULT true,
    `START_HOUR` TIME(0) NULL,
    `END_HOUR` TIME(0) NULL,

    PRIMARY KEY (`UID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `menu` (
    `UID` INTEGER NOT NULL,
    `MENU_ID` INTEGER NOT NULL,
    `FOOD_NAME` VARCHAR(50) NULL,
    `FOOD_ALLERGENS` VARCHAR(100) NULL,
    `PRICE` DECIMAL(10, 2) NULL,

    PRIMARY KEY (`UID`, `MENU_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `orders` (
    `ORDER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CUSTOMER_ID` INTEGER NULL,
    `KITCHEN_ID` INTEGER NULL,
    `DELIVERER_ID` INTEGER NULL,
    `ORDER_DATE` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `STATUS` VARCHAR(50) NULL DEFAULT 'PENDING',
    `TOTAL_AMOUNT` DECIMAL(10, 2) NULL,

    INDEX `CUSTOMER_ID`(`CUSTOMER_ID`),
    INDEX `DELIVERER_ID`(`DELIVERER_ID`),
    INDEX `KITCHEN_ID`(`KITCHEN_ID`),
    PRIMARY KEY (`ORDER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `users` (
    `UID` INTEGER NOT NULL AUTO_INCREMENT,
    `UNAME` VARCHAR(50) NOT NULL,
    `PWD` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(254) NULL,
    `ADDR` VARCHAR(100) NULL,
    `ROLE` VARCHAR(50) NOT NULL DEFAULT 'CUSTOMER',
    `BANK_TOKEN` VARCHAR(50) NULL,

    PRIMARY KEY (`UID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `customers` ADD CONSTRAINT `customers_ibfk_1` FOREIGN KEY (`UID`) REFERENCES `users`(`UID`) ON DELETE CASCADE ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `deliverers` ADD CONSTRAINT `deliverers_ibfk_1` FOREIGN KEY (`UID`) REFERENCES `users`(`UID`) ON DELETE CASCADE ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `kitchens` ADD CONSTRAINT `kitchens_ibfk_1` FOREIGN KEY (`UID`) REFERENCES `users`(`UID`) ON DELETE CASCADE ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `menu` ADD CONSTRAINT `menu_ibfk_1` FOREIGN KEY (`UID`) REFERENCES `kitchens`(`UID`) ON DELETE CASCADE ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `orders` ADD CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customers`(`UID`) ON DELETE SET NULL ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `orders` ADD CONSTRAINT `orders_ibfk_2` FOREIGN KEY (`KITCHEN_ID`) REFERENCES `kitchens`(`UID`) ON DELETE SET NULL ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `orders` ADD CONSTRAINT `orders_ibfk_3` FOREIGN KEY (`DELIVERER_ID`) REFERENCES `deliverers`(`UID`) ON DELETE SET NULL ON UPDATE RESTRICT;
